#cloud-config
# Cloud config for application servers

runcmd:
  # Install docker

  # Add Docker's official GPG key:
  - sudo apt-get update
  - sudo apt-get install ca-certificates curl gnupg
  - sudo install -m 0755 -d /etc/apt/keyrings
  - sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc

  # Add the repository to Apt sources:
  - echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu jammy stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
  - sudo apt-get update

  - sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

  - sudo usermod -aG docker ubuntu
  - sudo apt-get -y install vim

  # Run nginx
  - docker run -d -p 80:80 cloudgenius/nginx
